// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-workouts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared.ts
function requireUser(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new Error("Not authenticated. Connect this MCP server with OAuth first.");
  }
  const userId = ctx.getUserId();
  if (!userId) throw new Error("Could not resolve the signed-in user from the token.");
  return { db: supabaseForUser(ctx), userId };
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    structuredContent: payload
  };
}
function fail(message, extra) {
  const payload = { error: message, ...extra };
  return {
    content: [{ type: "text", text: JSON.stringify(payload) }],
    isError: true
  };
}
function isoDate(d) {
  return d.toISOString().slice(0, 10);
}
function daysAgo(days) {
  const d = /* @__PURE__ */ new Date();
  d.setUTCDate(d.getUTCDate() - days);
  return isoDate(d);
}
function startOfDayIso(date) {
  return (/* @__PURE__ */ new Date(`${date}T00:00:00.000Z`)).toISOString();
}
function endOfDayIso(date) {
  return (/* @__PURE__ */ new Date(`${date}T23:59:59.999Z`)).toISOString();
}
function estimate1RM(weightKg, reps) {
  if (!weightKg || !reps || reps <= 0) return 0;
  if (reps === 1) return round(weightKg);
  return round(weightKg * (1 + reps / 30));
}
function round(n, decimals = 1) {
  const f = 10 ** decimals;
  return Math.round(n * f) / f;
}
function normalizeName(str) {
  return str.toLowerCase().trim().replace(/[åä]/g, "a").replace(/ö/g, "o").replace(/[-_]/g, " ").replace(/\s+/g, " ");
}
function similarity(a, b) {
  const n1 = normalizeName(a);
  const n2 = normalizeName(b);
  if (n1 === n2) return 1;
  if (n1.includes(n2) || n2.includes(n1)) return 0.9;
  const w1 = n1.split(" ");
  const w2 = n2.split(" ");
  const common = w1.filter((w) => w2.some((o) => o.includes(w) || w.includes(o)));
  return common.length / Math.max(w1.length, w2.length) * 0.8;
}
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function resolveExercise(db, input) {
  const { data: exercises } = await db.from("exercises").select("id, name, is_cardio, muscle_groups");
  const list = exercises ?? [];
  if (UUID_RE.test(input.trim())) {
    const byId = list.find((e) => e.id === input.trim());
    if (byId) return { exercise: byId };
  }
  const normalized = normalizeName(input);
  const exact = list.find((e) => normalizeName(e.name) === normalized);
  if (exact) return { exercise: exact };
  const { data: aliases } = await db.from("exercise_aliases").select("exercise_id, alias");
  const aliasHit = (aliases ?? []).find(
    (a) => normalizeName(a.alias) === normalized
  );
  if (aliasHit) {
    const byAlias = list.find((e) => e.id === aliasHit.exercise_id);
    if (byAlias) return { exercise: byAlias };
  }
  const scored = list.map((e) => ({ e, score: similarity(e.name, input) })).sort((a, b) => b.score - a.score);
  if (scored[0] && scored[0].score >= 0.85) return { exercise: scored[0].e };
  return {
    exercise: null,
    suggestions: scored.filter((s) => s.score > 0.3).slice(0, 5).map((s) => ({ id: s.e.id, name: s.e.name }))
  };
}
var WORKOUT_TYPES = [
  "push",
  "pull",
  "legs",
  "full_body",
  "cardio",
  "upper",
  "lower",
  "custom"
];

// src/lib/mcp/tools/list-workouts.ts
var list_workouts_default = defineTool({
  name: "list_workouts",
  title: "List workouts",
  description: "Use when you need an overview of the user's training sessions in a date range, for example 'what did I train last week'. Returns compact summaries (id, date, type, duration, status, exercise names), newest first. Defaults to the last 4 weeks. Use get_workout for the full set-by-set detail of a single session.",
  inputSchema: {
    from: z.string().optional().describe("Start date, YYYY-MM-DD. Defaults to 28 days ago."),
    to: z.string().optional().describe("End date, YYYY-MM-DD. Defaults to today."),
    type: z.enum(WORKOUT_TYPES).optional().describe("Filter by workout type."),
    status: z.enum(["planned", "active", "completed", "any"]).optional().describe("Filter by status. Defaults to 'completed'. Use 'planned' to see upcoming planned sessions."),
    limit: z.number().int().optional().describe("Max results, default 20, max 100."),
    cursor: z.string().optional().describe("Opaque cursor from a previous response's next_cursor.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, status, limit, cursor }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const fromDate = from ?? daysAgo(28);
      const toDate = to ?? isoDate(/* @__PURE__ */ new Date());
      const pageSize = Math.min(Math.max(limit ?? 20, 1), 100);
      const offset = cursor ? Number.parseInt(cursor, 10) || 0 : 0;
      const effectiveStatus = status ?? "completed";
      let query = db.from("workout_sessions").select(
        "id, workout_type, custom_type_name, title, status, planned_date, source, started_at, ended_at, duration_seconds, rating, notes, workout_exercises(order_index, exercises(name))"
      ).gte("started_at", startOfDayIso(fromDate)).lte("started_at", endOfDayIso(toDate)).order("started_at", { ascending: false }).range(offset, offset + pageSize);
      if (type) query = query.eq("workout_type", type);
      if (effectiveStatus !== "any") query = query.eq("status", effectiveStatus);
      const { data, error } = await query;
      if (error) return fail(error.message);
      const rows = data ?? [];
      const hasMore = rows.length > pageSize;
      const page = rows.slice(0, pageSize);
      return ok({
        range: { from: fromDate, to: toDate },
        status: effectiveStatus,
        workouts: page.map((w) => ({
          id: w.id,
          title: w.title ?? w.custom_type_name ?? null,
          type: w.workout_type,
          status: w.status,
          source: w.source,
          planned_date: w.planned_date,
          started_at: w.started_at,
          ended_at: w.ended_at,
          duration_minutes: w.duration_seconds != null ? Math.round(w.duration_seconds / 60) : null,
          rating: w.rating,
          notes: w.notes,
          exercises: (w.workout_exercises ?? []).sort((a, b) => a.order_index - b.order_index).map((we) => we.exercises?.name).filter(Boolean)
        })),
        next_cursor: hasMore ? String(offset + pageSize) : null
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/get-workout.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_workout_default = defineTool2({
  name: "get_workout",
  title: "Get workout",
  description: "Use when you need every detail of one training session: exercises with muscle groups, all sets with weight, reps, warmup flag and RPE, cardio data, plus target values when the session came from a plan. Get the id from list_workouts.",
  inputSchema: {
    workout_id: z2.string().describe("The workout session id from list_workouts.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ workout_id }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const { data, error } = await db.from("workout_sessions").select(
        `id, workout_type, custom_type_name, title, status, planned_date, source, started_at, ended_at,
           duration_seconds, rating, notes,
           workout_exercises (
             id, order_index, superset_group, notes, is_completed,
             target_sets, target_reps, target_weight_kg, target_rpe,
             exercises ( id, name, muscle_groups, equipment_type, is_cardio ),
             exercise_sets ( id, set_number, weight_kg, reps, is_warmup, is_bodyweight, rpe, rir, notes, completed_at ),
             cardio_logs ( cardio_type, duration_seconds, distance_km, calories, avg_heart_rate, max_heart_rate, pace_sec_per_km, notes )
           )`
      ).eq("id", workout_id).maybeSingle();
      if (error) return fail(error.message);
      if (!data) return fail("Workout not found or not accessible.", { workout_id });
      const w = data;
      const exercises = (w.workout_exercises ?? []).sort((a, b) => a.order_index - b.order_index).map((we) => {
        const ex = we.exercises;
        const sets = (we.exercise_sets ?? []).sort(
          (a, b) => a.set_number - b.set_number
        );
        const working = sets.filter((s) => !s.is_warmup);
        return {
          id: we.id,
          exercise_id: ex?.id,
          name: ex?.name,
          muscle_groups: ex?.muscle_groups ?? [],
          equipment: ex?.equipment_type,
          is_cardio: ex?.is_cardio ?? false,
          superset_group: we.superset_group,
          is_completed: we.is_completed,
          notes: we.notes,
          target: we.target_sets || we.target_reps || we.target_weight_kg || we.target_rpe ? {
            sets: we.target_sets,
            reps: we.target_reps,
            weight_kg: we.target_weight_kg,
            rpe: we.target_rpe
          } : null,
          sets: sets.map((s) => ({
            set_number: s.set_number,
            weight_kg: s.weight_kg,
            reps: s.reps,
            is_warmup: s.is_warmup,
            is_bodyweight: s.is_bodyweight,
            rpe: s.rpe,
            rir: s.rir,
            notes: s.notes,
            completed_at: s.completed_at
          })),
          volume_kg: round(
            working.reduce((sum, s) => sum + (s.weight_kg ?? 0) * (s.reps ?? 0), 0)
          ),
          cardio: (we.cardio_logs ?? [])[0] ?? null
        };
      });
      return ok({
        id: w.id,
        title: w.title ?? w.custom_type_name ?? null,
        type: w.workout_type,
        status: w.status,
        source: w.source,
        planned_date: w.planned_date,
        started_at: w.started_at,
        ended_at: w.ended_at,
        duration_minutes: w.duration_seconds != null ? Math.round(w.duration_seconds / 60) : null,
        rating: w.rating,
        notes: w.notes,
        total_volume_kg: round(exercises.reduce((s, e) => s + e.volume_kg, 0)),
        exercises
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/get-exercise-history.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_exercise_history_default = defineTool3({
  name: "get_exercise_history",
  title: "Get exercise history",
  description: "Use when you need the progression for a single exercise over time, for example 'how has my squat developed'. Returns one entry per training day with the working sets and the best estimated 1RM that day. Cardio exercises return duration, distance, pace and heart rate instead of weight and reps. Names are alias-resolved, so 'db curl' and 'Dumbbell Curl' hit the same exercise.",
  inputSchema: {
    exercise: z3.string().describe("Exercise id or name (aliases are resolved)."),
    from: z3.string().optional().describe("Start date, YYYY-MM-DD. Defaults to 6 months ago."),
    to: z3.string().optional().describe("End date, YYYY-MM-DD. Defaults to today."),
    include_warmups: z3.boolean().optional().describe("Include warmup sets. Default false."),
    limit: z3.number().int().optional().describe("Max training days, default 50, max 200."),
    cursor: z3.string().optional().describe("Opaque cursor from a previous response.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ exercise, from, to, include_warmups, limit, cursor }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const resolved = await resolveExercise(db, exercise);
      if (!resolved.exercise) {
        return fail(
          `No exercise matches "${exercise}". Pick one of the suggestions or call list_exercises.`,
          { suggestions: resolved.suggestions }
        );
      }
      const ex = resolved.exercise;
      const fromDate = from ?? daysAgo(183);
      const toDate = to ?? isoDate(/* @__PURE__ */ new Date());
      const pageSize = Math.min(Math.max(limit ?? 50, 1), 200);
      const offset = cursor ? Number.parseInt(cursor, 10) || 0 : 0;
      const { data, error } = await db.from("workout_exercises").select(
        `id,
           workout_sessions!inner ( id, started_at, status ),
           exercise_sets ( set_number, weight_kg, reps, is_warmup, is_bodyweight, rpe, rir ),
           cardio_logs ( cardio_type, duration_seconds, distance_km, calories, avg_heart_rate, max_heart_rate, pace_sec_per_km )`
      ).eq("exercise_id", ex.id).eq("workout_sessions.status", "completed").gte("workout_sessions.started_at", startOfDayIso(fromDate)).lte("workout_sessions.started_at", endOfDayIso(toDate));
      if (error) return fail(error.message);
      const entries = (data ?? []).map((we) => {
        const session = we.workout_sessions;
        const allSets = (we.exercise_sets ?? []).sort(
          (a, b) => a.set_number - b.set_number
        );
        const sets = include_warmups ? allSets : allSets.filter((s) => !s.is_warmup);
        const cardio = (we.cardio_logs ?? [])[0] ?? null;
        if (ex.is_cardio) {
          return {
            workout_id: session.id,
            date: session.started_at,
            cardio: cardio ? {
              type: cardio.cardio_type,
              duration_minutes: cardio.duration_seconds != null ? round(cardio.duration_seconds / 60) : null,
              distance_km: cardio.distance_km,
              calories: cardio.calories,
              avg_heart_rate: cardio.avg_heart_rate,
              max_heart_rate: cardio.max_heart_rate,
              pace_sec_per_km: cardio.pace_sec_per_km
            } : null
          };
        }
        const best = sets.reduce(
          (acc, s) => Math.max(acc, estimate1RM(s.weight_kg ?? 0, s.reps ?? 0)),
          0
        );
        return {
          workout_id: session.id,
          date: session.started_at,
          sets: sets.map((s) => ({
            set_number: s.set_number,
            weight_kg: s.weight_kg,
            reps: s.reps,
            is_warmup: s.is_warmup,
            is_bodyweight: s.is_bodyweight,
            rpe: s.rpe,
            rir: s.rir
          })),
          top_weight_kg: sets.reduce((m, s) => Math.max(m, s.weight_kg ?? 0), 0) || null,
          volume_kg: round(
            sets.reduce((sum, s) => sum + (s.weight_kg ?? 0) * (s.reps ?? 0), 0)
          ),
          estimated_1rm_kg: best || null
        };
      }).filter((e) => ex.is_cardio ? e.cardio : e.sets.length > 0).sort((a, b) => a.date < b.date ? 1 : -1);
      const page = entries.slice(offset, offset + pageSize);
      return ok({
        exercise: {
          id: ex.id,
          name: ex.name,
          is_cardio: ex.is_cardio,
          muscle_groups: ex.muscle_groups
        },
        range: { from: fromDate, to: toDate },
        include_warmups: !!include_warmups,
        entries: page,
        next_cursor: offset + pageSize < entries.length ? String(offset + pageSize) : null
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/list-exercises.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_exercises_default = defineTool4({
  name: "list_exercises",
  title: "List exercises",
  description: "Use before planning a workout to see which exercises exist, with their canonical ids, names, aliases, muscle groups and equipment. Always plan with names from this catalog so no duplicate exercises are created.",
  inputSchema: {
    search: z4.string().optional().describe("Optional free-text filter on name or alias."),
    muscle_group: z4.string().optional().describe("Filter by muscle group, e.g. 'chest'."),
    is_cardio: z4.boolean().optional().describe("Only cardio (true) or only strength (false)."),
    limit: z4.number().int().optional().describe("Max results, default 100, max 300."),
    cursor: z4.string().optional().describe("Opaque cursor from a previous response.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, muscle_group, is_cardio, limit, cursor }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const pageSize = Math.min(Math.max(limit ?? 100, 1), 300);
      const offset = cursor ? Number.parseInt(cursor, 10) || 0 : 0;
      const [{ data: exercises, error }, { data: aliases }] = await Promise.all([
        db.from("exercises").select("id, name, description, muscle_groups, equipment_type, is_cardio, is_custom").order("name"),
        db.from("exercise_aliases").select("exercise_id, alias")
      ]);
      if (error) return fail(error.message);
      const aliasMap = /* @__PURE__ */ new Map();
      for (const a of aliases ?? []) {
        const arr = aliasMap.get(a.exercise_id) ?? [];
        arr.push(a.alias);
        aliasMap.set(a.exercise_id, arr);
      }
      let list = (exercises ?? []).map((e) => ({
        id: e.id,
        name: e.name,
        aliases: aliasMap.get(e.id) ?? [],
        muscle_groups: e.muscle_groups ?? [],
        equipment: e.equipment_type,
        is_cardio: e.is_cardio,
        is_custom: e.is_custom
      }));
      if (typeof is_cardio === "boolean") list = list.filter((e) => e.is_cardio === is_cardio);
      if (muscle_group) {
        const mg = muscle_group.toLowerCase();
        list = list.filter((e) => e.muscle_groups.some((m) => m.toLowerCase() === mg));
      }
      if (search) {
        const q = normalizeName(search);
        list = list.filter(
          (e) => normalizeName(e.name).includes(q) || e.aliases.some((a) => normalizeName(a).includes(q))
        );
      }
      return ok({
        total: list.length,
        exercises: list.slice(offset, offset + pageSize),
        next_cursor: offset + pageSize < list.length ? String(offset + pageSize) : null
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/create-planned-workout.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var exerciseInput = z5.object({
  exercise: z5.string().describe("Exercise name or id from list_exercises."),
  sets: z5.number().int().optional().describe("Number of planned sets."),
  target_reps: z5.string().optional().describe("Target reps as text, e.g. '5' or '8-10'."),
  target_weight_kg: z5.number().optional().describe("Target working weight in kilograms."),
  target_rpe: z5.number().min(6).max(10).optional().describe("Target RPE for the exercise, 6-10 (half steps allowed)."),
  notes: z5.string().optional().describe("Short coaching note for this exercise.")
});
var create_planned_workout_default = defineTool5({
  name: "create_planned_workout",
  title: "Create planned workout",
  description: "Use to write a planned training session into the app for a future date, so the user can open and run it. Exercise names must resolve against the existing catalog; unknown names return an error with suggestions instead of creating duplicates. Always check list_exercises first.",
  inputSchema: {
    date: z5.string().describe("Planned date, YYYY-MM-DD."),
    workout_type: z5.enum(WORKOUT_TYPES).describe("Workout type."),
    title: z5.string().optional().describe("Short session title, e.g. 'Ben med Tina'."),
    notes: z5.string().optional().describe("Session-level notes for the user."),
    exercises: z5.array(exerciseInput).describe("Planned exercises in order.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ date, workout_type, title, notes, exercises }, ctx) => {
    try {
      const { db, userId } = requireUser(ctx);
      if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return fail("date must be YYYY-MM-DD.");
      if (!exercises.length) return fail("At least one exercise is required.");
      const resolvedList = [];
      for (const item of exercises) {
        const r = await resolveExercise(db, item.exercise);
        if (!r.exercise) {
          return fail(
            `No exercise matches "${item.exercise}". Use one of the suggestions or call list_exercises.`,
            { unresolved: item.exercise, suggestions: r.suggestions }
          );
        }
        resolvedList.push({ id: r.exercise.id, input: item });
      }
      const { data: session, error: sessionError } = await db.from("workout_sessions").insert({
        user_id: userId,
        workout_type,
        title: title ?? null,
        notes: notes ?? null,
        status: "planned",
        source: "mcp",
        planned_date: date,
        is_active: false,
        started_at: `${date}T12:00:00.000Z`
      }).select("id").single();
      if (sessionError) return fail(sessionError.message);
      const rows = resolvedList.map((r, index) => ({
        workout_session_id: session.id,
        exercise_id: r.id,
        order_index: index,
        target_sets: r.input.sets ?? null,
        target_reps: r.input.target_reps ?? null,
        target_weight_kg: r.input.target_weight_kg ?? null,
        target_rpe: r.input.target_rpe ?? null,
        notes: r.input.notes ?? null
      }));
      const { error: exError } = await db.from("workout_exercises").insert(rows);
      if (exError) {
        await db.from("workout_sessions").delete().eq("id", session.id);
        return fail(exError.message);
      }
      return ok({
        workout_id: session.id,
        status: "planned",
        date,
        workout_type,
        title: title ?? null,
        exercise_count: rows.length
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/update-planned-workout.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var exerciseInput2 = z6.object({
  exercise: z6.string().describe("Exercise name or id from list_exercises."),
  sets: z6.number().int().optional().describe("Number of planned sets."),
  target_reps: z6.string().optional().describe("Target reps as text, e.g. '5' or '8-10'."),
  target_weight_kg: z6.number().optional().describe("Target working weight in kilograms."),
  target_rpe: z6.number().min(6).max(10).optional().describe("Target RPE for the exercise, 6-10 (half steps allowed)."),
  notes: z6.string().optional().describe("Short coaching note for this exercise.")
});
var update_planned_workout_default = defineTool6({
  name: "update_planned_workout",
  title: "Update planned workout",
  description: "Use to change a session that is still planned: its date, type, title, notes, or the full exercise list. Completed and active sessions cannot be modified. Passing 'exercises' replaces the whole planned exercise list.",
  inputSchema: {
    workout_id: z6.string().describe("Id of the planned workout."),
    date: z6.string().optional().describe("New planned date, YYYY-MM-DD."),
    workout_type: z6.enum(WORKOUT_TYPES).optional().describe("New workout type."),
    title: z6.string().optional().describe("New title."),
    notes: z6.string().optional().describe("New session notes."),
    exercises: z6.array(exerciseInput2).optional().describe("Replaces the full planned exercise list when provided.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ workout_id, date, workout_type, title, notes, exercises }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const { data: existing, error: readError } = await db.from("workout_sessions").select("id, status").eq("id", workout_id).maybeSingle();
      if (readError) return fail(readError.message);
      if (!existing) return fail("Workout not found or not accessible.", { workout_id });
      if (existing.status !== "planned") {
        return fail(
          `Only planned workouts can be updated. This one has status "${existing.status}".`
        );
      }
      const patch = {};
      if (date) {
        if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return fail("date must be YYYY-MM-DD.");
        patch.planned_date = date;
        patch.started_at = `${date}T12:00:00.000Z`;
      }
      if (workout_type) patch.workout_type = workout_type;
      if (title !== void 0) patch.title = title;
      if (notes !== void 0) patch.notes = notes;
      if (Object.keys(patch).length > 0) {
        const { error } = await db.from("workout_sessions").update(patch).eq("id", workout_id);
        if (error) return fail(error.message);
      }
      let exerciseCount = null;
      if (exercises) {
        const resolvedList = [];
        for (const item of exercises) {
          const r = await resolveExercise(db, item.exercise);
          if (!r.exercise) {
            return fail(
              `No exercise matches "${item.exercise}". Use one of the suggestions or call list_exercises.`,
              { unresolved: item.exercise, suggestions: r.suggestions }
            );
          }
          resolvedList.push({ id: r.exercise.id, input: item });
        }
        await db.from("workout_exercises").delete().eq("workout_session_id", workout_id);
        if (resolvedList.length) {
          const { error } = await db.from("workout_exercises").insert(
            resolvedList.map((r, index) => ({
              workout_session_id: workout_id,
              exercise_id: r.id,
              order_index: index,
              target_sets: r.input.sets ?? null,
              target_reps: r.input.target_reps ?? null,
              target_weight_kg: r.input.target_weight_kg ?? null,
              target_rpe: r.input.target_rpe ?? null,
              notes: r.input.notes ?? null
            }))
          );
          if (error) return fail(error.message);
        }
        exerciseCount = resolvedList.length;
      }
      return ok({ workout_id, updated: true, exercise_count: exerciseCount });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/delete-planned-workout.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^3.25.76";
var delete_planned_workout_default = defineTool7({
  name: "delete_planned_workout",
  title: "Delete planned workout",
  description: "Use to remove a session that is still planned and has not been performed. Completed and active sessions can never be deleted through this server.",
  inputSchema: {
    workout_id: z7.string().describe("Id of the planned workout to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true },
  handler: async ({ workout_id }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const { data: existing, error: readError } = await db.from("workout_sessions").select("id, status").eq("id", workout_id).maybeSingle();
      if (readError) return fail(readError.message);
      if (!existing) return fail("Workout not found or not accessible.", { workout_id });
      if (existing.status !== "planned") {
        return fail(
          `Only planned workouts can be deleted. This one has status "${existing.status}".`
        );
      }
      const { error } = await db.from("workout_sessions").delete().eq("id", workout_id).eq("status", "planned");
      if (error) return fail(error.message);
      return ok({ workout_id, deleted: true });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/get-body-weight.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z8 } from "npm:zod@^3.25.76";
var get_body_weight_default = defineTool8({
  name: "get_body_weight",
  title: "Get body weight",
  description: "Use when body weight matters for the coaching, for example bodyweight progression, cutting or bulking. Returns logged weights in kilograms for a date range, newest first, plus the change over the range.",
  inputSchema: {
    from: z8.string().optional().describe("Start date, YYYY-MM-DD. Defaults to 180 days ago."),
    to: z8.string().optional().describe("End date, YYYY-MM-DD. Defaults to today."),
    limit: z8.number().int().optional().describe("Max entries, default 100, max 365."),
    cursor: z8.string().optional().describe("Opaque cursor from a previous response.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit, cursor }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const fromDate = from ?? daysAgo(180);
      const toDate = to ?? isoDate(/* @__PURE__ */ new Date());
      const pageSize = Math.min(Math.max(limit ?? 100, 1), 365);
      const offset = cursor ? Number.parseInt(cursor, 10) || 0 : 0;
      const { data, error } = await db.from("body_weight_logs").select("weight_kg, logged_at, notes").gte("logged_at", fromDate).lte("logged_at", toDate).order("logged_at", { ascending: false }).range(offset, offset + pageSize);
      if (error) return fail(error.message);
      const rows = data ?? [];
      const hasMore = rows.length > pageSize;
      const page = rows.slice(0, pageSize);
      const latest = page[0];
      const oldest = page[page.length - 1];
      return ok({
        range: { from: fromDate, to: toDate },
        unit: "kg",
        latest_kg: latest ? Number(latest.weight_kg) : null,
        change_kg: latest && oldest && page.length > 1 ? round(Number(latest.weight_kg) - Number(oldest.weight_kg)) : null,
        entries: page.map((r) => ({
          date: r.logged_at,
          weight_kg: Number(r.weight_kg),
          notes: r.notes
        })),
        next_cursor: hasMore ? String(offset + pageSize) : null
      });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/tools/get-week-summary.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z9 } from "npm:zod@^3.25.76";
function isoWeekKey(date) {
  const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((d.getTime() - yearStart.getTime()) / 864e5 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(week).padStart(2, "0")}`;
}
var get_week_summary_default = defineTool9({
  name: "get_week_summary",
  title: "Get weekly summary",
  description: "Use for a high-level training load overview: sessions, working sets and volume per muscle group, grouped by ISO week. Good for spotting neglected muscle groups or a drop in volume.",
  inputSchema: {
    from: z9.string().optional().describe("Start date, YYYY-MM-DD. Defaults to 8 weeks ago."),
    to: z9.string().optional().describe("End date, YYYY-MM-DD. Defaults to today.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    try {
      const { db } = requireUser(ctx);
      const fromDate = from ?? daysAgo(56);
      const toDate = to ?? isoDate(/* @__PURE__ */ new Date());
      const { data, error } = await db.from("workout_sessions").select(
        `id, started_at, workout_type, duration_seconds,
           workout_exercises ( exercises ( muscle_groups, is_cardio ), exercise_sets ( weight_kg, reps, is_warmup ) )`
      ).eq("status", "completed").gte("started_at", startOfDayIso(fromDate)).lte("started_at", endOfDayIso(toDate)).order("started_at", { ascending: false });
      if (error) return fail(error.message);
      const weeks = /* @__PURE__ */ new Map();
      for (const session of data ?? []) {
        const key = isoWeekKey(new Date(session.started_at));
        const bucket = weeks.get(key) ?? {
          week: key,
          workouts: 0,
          working_sets: 0,
          duration_minutes: 0,
          total_volume_kg: 0,
          volume_by_muscle_kg: {}
        };
        bucket.workouts += 1;
        bucket.duration_minutes += Math.round((session.duration_seconds ?? 0) / 60);
        for (const we of session.workout_exercises ?? []) {
          const muscles = we.exercises?.muscle_groups ?? [];
          for (const s of we.exercise_sets ?? []) {
            if (s.is_warmup) continue;
            bucket.working_sets += 1;
            const volume = (s.weight_kg ?? 0) * (s.reps ?? 0);
            bucket.total_volume_kg += volume;
            if (volume > 0 && muscles.length) {
              const share = volume / muscles.length;
              for (const m of muscles) {
                bucket.volume_by_muscle_kg[m] = (bucket.volume_by_muscle_kg[m] ?? 0) + share;
              }
            }
          }
        }
        weeks.set(key, bucket);
      }
      const result = [...weeks.values()].map((w) => ({
        ...w,
        total_volume_kg: round(w.total_volume_kg),
        volume_by_muscle_kg: Object.fromEntries(
          Object.entries(w.volume_by_muscle_kg).map(([k, v]) => [k, round(v)]).sort((a, b) => b[1] - a[1])
        )
      })).sort((a, b) => a.week < b.week ? 1 : -1);
      return ok({ range: { from: fromDate, to: toDate }, unit: "kg", weeks: result });
    } catch (e) {
      return fail(e instanceof Error ? e.message : "Unknown error");
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "aoibiphmvcffolrznqmn";
var mcp_default = defineMcp({
  name: "gymbro3000",
  title: "GymBro3000",
  version: "0.1.0",
  instructions: "Tools for the GymBro3000 gym log. Read the user's real training data before giving advice: list_workouts for recent sessions, get_workout for full set-by-set detail, get_exercise_history for progression on one lift, get_week_summary for load per muscle group, get_body_weight for bodyweight trend. To program ahead, call list_exercises first and then create_planned_workout with names from that catalog; planned sessions can be changed with update_planned_workout and removed with delete_planned_workout. Completed sessions are read-only. All weights are kilograms, all timestamps ISO 8601.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_workouts_default,
    get_workout_default,
    get_exercise_history_default,
    list_exercises_default,
    create_planned_workout_default,
    update_planned_workout_default,
    delete_planned_workout_default,
    get_body_weight_default,
    get_week_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
